# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         mp3rename
version:      1.15
version_from: script/mp3rename
installdirs:  site
requires:
    Getopt::Long:                  2.33
    MP3::Info:                     1.02
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
